### ISSUE TITLE
Desktop version does not stop the news

### ISSUE THREAD

**Issue by valdr** [MycroftAI/skill-npr-news#6]
Using CLI input (github clone debug-mode), after I ask Mycroft to tell me the news, NPR starts, but mycroft does nothing when I type "end news" or "stop news". the whole report finishes.

All I get is the following:

```
- DEBUG - {"type": "complete_intent_failure", "data": {}, "context": null}
- DEBUG - {"type": "recognizer_loop:utterance", "data": {"lang": "en-us", "utterances": ["end news"]}, "context": null}
- DEBUG - {"type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": 7287314279880443391, "utterances": ["end news"]}, "context": null}
- DEBUG - {"type": "skill.converse.response", "data": {"skill_id": 7287314279880443391, "result": false}, "context": null}
~~~~false, "entities": [{"confidence": 1.0, "data": [["news", "NPRNewsKeyword"]], "key": "news", "match": "news"}], "key": "news", "match": "news"}], "utterance": "end news"}, "context": {"target": null}}
- DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "NPRNewsSkill.handle_stop"}, "context": null}
- DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"handler": "NPRNewsSkill.handle_stop"}, "context": null}

```

**Comment by akailash** [comment]
This is a bug due to introduction of audioservice without its corresponding stop mechanism in stop(). I think audioservice's pause() function is not working and it doesn't have a stop() function defined. Directly calling `self.emitter.emit(Message('mycroft.audio.service.stop'))`  works, but I'd rather have a stop() function in audioservice.py which can be called by various skills.

Alternatively, if you use the [playback control skill](https://github.com/MycroftAI/skill-playback-control), it should stop playback with just the keyword "stop".
